
import { Inter } from "next/font/google"; //Esta linea importa la fuente "Inter" desde Google Fonts usando la utilidad integrada de Next.js.


const inter = Inter({ subsets: ["latin"] }); //configuracion fuente inter

export const metadata = {
  title: "Empleados App",
  description: "Generated by create next app",
};


//componente layout envuelve toda la estrutura de la app
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
